version: "0.2"
words:
  - actix
  - alpn
  - clippy
  - Deque
  - docsrs
  - HMAC
  - JWTs
  - letsencrypt
  - MSRV
  - nextest
  - nixos
  - nixpkgs
  - oneshot
  - pemfile
  - pkgs
  - pkix
  - rcgen
  - reqwest
  - rustdoc
  - rustls
  - serde
  - stdenv
  - subproblems
  - taplo
  - ureq
  - webpki
