exclude = ["target/*"]
include = ["**/*.toml"]

[formatting]
column_width = 100

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "dependencies",
    "*-dependencies",
    "workspace.dependencies",
    "workspace.*-dependencies",
    "target.*.dependencies",
    "target.*.*-dependencies",
]
formatting.reorder_keys = true
formatting.align_comments = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "dependencies.*",
    "*-dependencies.*",
    "workspace.dependencies.*",
    "workspace.*-dependencies.*",
    "target.*.dependencies",
    "target.*.*-dependencies",
]
formatting.reorder_keys = false
formatting.align_comments = false
